#ifndef __BLE_HEART_RATE_SERVICE_H
#define __BLE_HEART_RATE_SERVICE_H
#include "include.h"

// Heart Rate  0x180D
// PRIMARY_SERVICE, ORG_BLUETOOTH_SERVICE_HEART_RATE
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_HEART_RATE_MEASUREMENT, DYNAMIC | NOTIFY,
// CLIENT_CHARACTERISTIC_CONFIGURATION, READ | WRITE,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_BODY_SENSOR_LOCATION, DYNAMIC | READ,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_HEART_RATE_CONTROL_POINT, DYNAMIC | WRITE,

//
// list service handle ranges
//
#define ATT_SERVICE_ORG_BLUETOOTH_SERVICE_HEART_RATE_START_HANDLE 0x0073
#define ATT_SERVICE_ORG_BLUETOOTH_SERVICE_HEART_RATE_END_HANDLE 0x007a

//
// list mapping between characteristics and handles
//
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_HEART_RATE_MEASUREMENT_01_VALUE_HANDLE 0x0075
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_HEART_RATE_MEASUREMENT_01_CLIENT_CONFIGURATION_HANDLE 0x0076
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_BODY_SENSOR_LOCATION_01_VALUE_HANDLE 0x0078
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_HEART_RATE_CONTROL_POINT_01_VALUE_HANDLE 0x007a

typedef struct{
    uint8_t meas_val[2];
    uint16_t meas_client_cfg;
}ble_heart_rate_var_t;

void ble_heart_rate_service_init(void);
void ble_heart_rate_service_proc(void);
void ble_heart_rate_service_measurement_notify(uint8_t *buf, uint16_t buf_size);
#endif
