#ifndef __BLE_WEIGHT_SCAL_SERVICE_H
#define __BLE_WEIGHT_SCAL_SERVICE_H
#include "include.h"

// Weight Scale  0x181D
// PRIMARY_SERVICE, ORG_BLUETOOTH_SERVICE_WEIGHT_SCALE
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_WEIGHT, DYNAMIC | READ,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_WEIGHT_MEASUREMENT, INDICATE,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_WEIGHT_SCALE_FEATURE, DYNAMIC | READ,

//
// list service handle ranges
//
#define ATT_SERVICE_ORG_BLUETOOTH_SERVICE_WEIGHT_SCALE_START_HANDLE 0x00c1
#define ATT_SERVICE_ORG_BLUETOOTH_SERVICE_WEIGHT_SCALE_END_HANDLE 0x00c8

//
// list mapping between characteristics and handles
//
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_WEIGHT_01_VALUE_HANDLE 0x00c3
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_WEIGHT_MEASUREMENT_01_VALUE_HANDLE 0x00c5
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_WEIGHT_MEASUREMENT_01_CLIENT_CONFIGURATION_HANDLE 0x00c6
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_WEIGHT_SCALE_FEATURE_01_VALUE_HANDLE 0x00c8

typedef struct{
    uint8_t feature[4];
    uint16_t measurement_client_cfg;
}ble_weight_scale_var_t;

void ble_weight_scale_service_init(void);
void ble_weight_scale_service_proc(void);
void ble_weight_scale_service_measurement_indicate(uint8_t *buf, uint16_t buf_size);
#endif
