#ifndef __BLE_DEVICE_TIME_SERVICE_H
#define __BLE_DEVICE_TIME_SERVICE_H
#include "include.h"

// Device Time 0x1847
// PRIMARY_SERVICE, ORG_BLUETOOTH_SERVICE_DEVICE_TIME
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_DEVICE_TIME_FEATURE_, DYNAMIC | READ,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_DEVICE_TIME_PARAMETERS_, DYNAMIC | READ,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_DEVICE_TIME_CONTROL_POINT_, DYNAMIC | WRITE | INDICATE,
// CLIENT_CHARACTERISTIC_CONFIGURATION, READ | WRITE,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_DEVICE_TIME, DYNAMIC | READ | INDICATE,
// CLIENT_CHARACTERISTIC_CONFIGURATION, READ | WRITE,

//
// list service handle ranges
//
#define ATT_SERVICE_ORG_BLUETOOTH_SERVICE_DEVICE_TIME_START_HANDLE 0x0042
#define ATT_SERVICE_ORG_BLUETOOTH_SERVICE_DEVICE_TIME_END_HANDLE 0x004c

//
// list mapping between characteristics and handles
//
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_DEVICE_TIME_FEATURE__01_VALUE_HANDLE 0x0044
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_DEVICE_TIME_PARAMETERS__01_VALUE_HANDLE 0x0046
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_DEVICE_TIME_CONTROL_POINT__01_VALUE_HANDLE 0x0048
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_DEVICE_TIME_CONTROL_POINT__01_CLIENT_CONFIGURATION_HANDLE 0x0049
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_DEVICE_TIME_01_VALUE_HANDLE 0x004b
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_DEVICE_TIME_01_CLIENT_CONFIGURATION_HANDLE 0x004c

typedef struct{
    uint8_t feature[4];
    uint8_t dt_parameters[2];
    uint8_t dev_time[8];
    uint16_t time_client_cfg;
    uint16_t ctr_point_client_cfg;
}ble_device_time_var_t;

void ble_device_time_service_init(void);
void ble_device_time_service_proc(void);
void ble_device_time_service_control_point_indicate(uint8_t *buf, uint16_t buf_size);
#endif
