#ifndef __BLE_GLUCOSE_SERVICE_H
#define __BLE_GLUCOSE_SERVICE_H
#include "include.h"

// Glucose 0x1808
// PRIMARY_SERVICE, ORG_BLUETOOTH_SERVICE_GLUCOSE
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_GLUCOSE_FEATURE, DYNAMIC | READ,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_GLUCOSE_MEASUREMENT, DYNAMIC | NOTIFY,
// CLIENT_CHARACTERISTIC_CONFIGURATION, READ | WRITE,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_RECORD_ACCESS_CONTROL_POINT, DYNAMIC | WRITE | INDICATE,
// CLIENT_CHARACTERISTIC_CONFIGURATION, READ | WRITE,

//
// list service handle ranges
//
#define ATT_SERVICE_ORG_BLUETOOTH_SERVICE_GLUCOSE_START_HANDLE 0x004d
#define ATT_SERVICE_ORG_BLUETOOTH_SERVICE_GLUCOSE_END_HANDLE 0x0055

//
// list mapping between characteristics and handles
//
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_GLUCOSE_FEATURE_01_VALUE_HANDLE 0x004f
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_GLUCOSE_MEASUREMENT_01_VALUE_HANDLE 0x0051
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_GLUCOSE_MEASUREMENT_01_CLIENT_CONFIGURATION_HANDLE 0x0052
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_RECORD_ACCESS_CONTROL_POINT_01_VALUE_HANDLE 0x0054
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_RECORD_ACCESS_CONTROL_POINT_01_CLIENT_CONFIGURATION_HANDLE 0x0055

typedef struct{
    uint8_t feature[2];
    uint16_t meas_client_cfg;
    uint16_t ctr_point_client_cfg;
}ble_glucose_var_t;

void ble_glucose_service_init(void);
void ble_glucose_service_proc(void);
void ble_glucose_service_measurement_notify(uint8_t *buf, uint16_t buf_size);
void ble_glucose_service_record_access_control_point_indicate(uint8_t *buf, uint16_t buf_size);
#endif
