#ifndef __BLE_BLOOD_PRESSURE_SERVICE_H
#define __BLE_BLOOD_PRESSURE_SERVICE_H
#include "include.h"

// Blood Pressure 0x1810
// PRIMARY_SERVICE, ORG_BLUETOOTH_SERVICE_BLOOD_PRESSURE
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_BLOOD_PRESSURE_MEASUREMENT, DYNAMIC | INDICATE,
// CLIENT_CHARACTERISTIC_CONFIGURATION, READ | WRITE,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_BLOOD_PRESSURE_FEATURE, DYNAMIC | READ,

//
// list service handle ranges
//
#define ATT_SERVICE_ORG_BLUETOOTH_SERVICE_BLOOD_PRESSURE_START_HANDLE 0x000d
#define ATT_SERVICE_ORG_BLUETOOTH_SERVICE_BLOOD_PRESSURE_END_HANDLE 0x0012

//
// list mapping between characteristics and handles
//
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_BLOOD_PRESSURE_MEASUREMENT_01_VALUE_HANDLE 0x000f
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_BLOOD_PRESSURE_MEASUREMENT_01_CLIENT_CONFIGURATION_HANDLE 0x0010
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_BLOOD_PRESSURE_FEATURE_01_VALUE_HANDLE 0x0012


typedef struct{
    uint8_t feature[2];
    uint16_t meas_client_cfg;
}ble_blood_pressure_var_t;

void ble_blood_pressure_service_init(void);
void ble_blood_pressure_service_proc(void);
void ble_blood_pressure_service_meas_indicate(uint8_t *buf, uint16_t buf_size);
#endif
