#ifndef __BLE_BOND_MANAGEMENT_SERVICE_H
#define __BLE_BOND_MANAGEMENT_SERVICE_H
#include "include.h"

// Bond Management 0x181E
// PRIMARY_SERVICE, ORG_BLUETOOTH_SERVICE_BOND_MANAGEMENT
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_BOND_MANAGEMENT_CONTROL_POINT, DYNAMIC | WRITE,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_BOND_MANAGEMENT_FEATURE, DYNAMIC | READ,

//
// list service handle ranges
//
#define ATT_SERVICE_ORG_BLUETOOTH_SERVICE_BOND_MANAGEMENT_START_HANDLE 0x0013
#define ATT_SERVICE_ORG_BLUETOOTH_SERVICE_BOND_MANAGEMENT_END_HANDLE 0x0017

//
// list mapping between characteristics and handles
//
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_BOND_MANAGEMENT_CONTROL_POINT_01_VALUE_HANDLE 0x0015
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_BOND_MANAGEMENT_FEATURE_01_VALUE_HANDLE 0x0017

typedef struct{
    uint8_t feature[3];
}ble_bond_management_var_t;

void ble_bond_management_service_init(void);
void ble_bond_management_service_proc(void);
#endif
