#ifndef __BLE_REFERENCE_TIME_SERVICE_H
#define __BLE_REFERENCE_TIME_SERVICE_H
#include "include.h"

// Reference Time  0x1806
// PRIMARY_SERVICE, ORG_BLUETOOTH_SERVICE_REFERENCE_TIME_UPDATE
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_TIME_UPDATE_CONTROL_POINT, DYNAMIC | WRITE_WITHOUT_RESPONSE,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_TIME_UPDATE_STATE, DYNAMIC | READ,

//
// list service handle ranges
//
#define ATT_SERVICE_ORG_BLUETOOTH_SERVICE_REFERENCE_TIME_UPDATE_START_HANDLE 0x00b3
#define ATT_SERVICE_ORG_BLUETOOTH_SERVICE_REFERENCE_TIME_UPDATE_END_HANDLE 0x00b7

//
// list mapping between characteristics and handles
//
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_TIME_UPDATE_CONTROL_POINT_01_VALUE_HANDLE 0x00b5
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_TIME_UPDATE_STATE_01_VALUE_HANDLE 0x00b7

typedef struct{
    uint16_t update_val;
    uint16_t update_sta;
}ble_reference_time_var_t;

void ble_reference_time_service_init(void);
void ble_reference_time_service_proc(void);
#endif
