#ifndef __BLE_CYCLING_POWER_SERVICE_H
#define __BLE_CYCLING_POWER_SERVICE_H
#include "include.h"

// Cycling Power 0x1818
// PRIMARY_SERVICE, ORG_BLUETOOTH_SERVICE_CYCLING_POWER
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_CYCLING_POWER_MEASUREMENT, DYNAMIC | NOTIFY,
// CLIENT_CHARACTERISTIC_CONFIGURATION, READ | WRITE,
// SERVER_CHARACTERISTIC_CONFIGURATION, READ | WRITE,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_CYCLING_POWER_FEATURE, DYNAMIC | READ,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_SENSOR_LOCATION, DYNAMIC | READ,

//
// list service handle ranges
//
#define ATT_SERVICE_ORG_BLUETOOTH_SERVICE_CYCLING_POWER_START_HANDLE 0x001e
#define ATT_SERVICE_ORG_BLUETOOTH_SERVICE_CYCLING_POWER_END_HANDLE 0x0026

//
// list mapping between characteristics and handles
//
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_CYCLING_POWER_MEASUREMENT_01_VALUE_HANDLE 0x0020
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_CYCLING_POWER_MEASUREMENT_01_CLIENT_CONFIGURATION_HANDLE 0x0021
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_CYCLING_POWER_MEASUREMENT_01_SERVER_CONFIGURATION_HANDLE 0x0022
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_CYCLING_POWER_FEATURE_01_VALUE_HANDLE 0x0024
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_SENSOR_LOCATION_01_VALUE_HANDLE 0x0026

typedef struct {
    uint8_t feature[4];
    uint16_t server_cfg;
    uint16_t client_cfg;
} ble_cycling_power_var_t;

void ble_cycling_power_service_init(void);
void ble_cycling_power_service_proc(void);
void ble_cycling_power_service_client_notify(uint8_t *buf, uint16_t buf_size);
#endif
