#ifndef __BLE_GAP_SERVICE_H
#define __BLE_GAP_SERVICE_H
#include "include.h"

// GAP 0x1800
// PRIMARY_SERVICE, ORG_BLUETOOTH_SERVICE_GENERIC_ACCESS
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_ENCRYPTED_DATA, READ | INDICATE | DYNAMIC,

//
// list service handle ranges
//
#define ATT_SERVICE_ORG_BLUETOOTH_SERVICE_GENERIC_ACCESS_START_HANDLE 0x00d8
#define ATT_SERVICE_ORG_BLUETOOTH_SERVICE_GENERIC_ACCESS_END_HANDLE 0x00db
//
// list mapping between characteristics and handles
//
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_ENCRYPTED_DATA_01_VALUE_HANDLE 0x00da
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_ENCRYPTED_DATA_01_CLIENT_CONFIGURATION_HANDLE 0x00db

void ble_gap_service_init(void);
void ble_gap_service_proc(void);
#endif
