#ifndef __BLE_PULSE_OXIMETE_SERVICE_H
#define __BLE_PULSE_OXIMETE_SERVICE_H
#include "include.h"

// Pulse Oximeter  0x1822
// PRIMARY_SERVICE, ORG_BLUETOOTH_SERVICE_PULSE_OXIMETER
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_PLX_CONTINUOUS_MEASUREMENT, NOTIFY,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_PLX_FEATURES, DYNAMIC | READ,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_PLX_SPOT_CHECK_MEASUREMENT, INDICATE,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_PULSE_OXIMETRY_CONTROL_POINT, DYNAMIC | INDICATE | WRITE,

//
// list service handle ranges
//
#define ATT_SERVICE_ORG_BLUETOOTH_SERVICE_PULSE_OXIMETER_START_HANDLE 0x00a7
#define ATT_SERVICE_ORG_BLUETOOTH_SERVICE_PULSE_OXIMETER_END_HANDLE 0x00b2

//
// list mapping between characteristics and handles
//
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_PLX_CONTINUOUS_MEASUREMENT_01_VALUE_HANDLE 0x00a9
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_PLX_CONTINUOUS_MEASUREMENT_01_CLIENT_CONFIGURATION_HANDLE 0x00aa
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_PLX_FEATURES_01_VALUE_HANDLE 0x00ac
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_PLX_SPOT_CHECK_MEASUREMENT_01_VALUE_HANDLE 0x00ae
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_PLX_SPOT_CHECK_MEASUREMENT_01_CLIENT_CONFIGURATION_HANDLE 0x00af
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_PULSE_OXIMETRY_CONTROL_POINT_01_VALUE_HANDLE 0x00b1
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_PULSE_OXIMETRY_CONTROL_POINT_01_CLIENT_CONFIGURATION_HANDLE 0x00b2

typedef struct{
    uint8_t feature[2];
    uint16_t ctn_meas_client_cfg;
    uint16_t check_meas_client_cfg;
    uint16_t ctl_point_client_cfg;
}ble_pulse_oximeter_var_t;

void ble_pulse_oximeter_service_init(void);
void ble_pulse_oximeter_service_proc(void);
void ble_pulse_oximeter_service_comtinuous_masurement_notify(uint8_t *buf, uint16_t buf_size);
void ble_pulse_oximeter_service_spot_check_masurement_indicate(uint8_t *buf, uint16_t buf_size);
void ble_pulse_oximeter_service_control_point_indicate(uint8_t *buf, uint16_t buf_size);
#endif
