#ifndef __BLE_SCAN_PARAM_SERVICE_H
#define __BLE_SCAN_PARAM_SERVICE_H
#include "include.h"

// Scan Param  0x1813
// PRIMARY_SERVICE, ORG_BLUETOOTH_SERVICE_SCAN_PARAMETERS
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_SCAN_INTERVAL_WINDOW, DYNAMIC | WRITE_WITHOUT_RESPONSE,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_SCAN_REFRESH, DYNAMIC | NOTIFY,

//
// list service handle ranges
//
#define ATT_SERVICE_ORG_BLUETOOTH_SERVICE_SCAN_PARAMETERS_START_HANDLE 0x00b8
#define ATT_SERVICE_ORG_BLUETOOTH_SERVICE_SCAN_PARAMETERS_END_HANDLE 0x00bd

//
// list mapping between characteristics and handles
//
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_SCAN_INTERVAL_WINDOW_01_VALUE_HANDLE 0x00ba
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_SCAN_REFRESH_01_VALUE_HANDLE 0x00bc
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_SCAN_REFRESH_01_CLIENT_CONFIGURATION_HANDLE 0x00bd

typedef struct{
    uint16_t scan_interval;
}ble_scan_param_var_t;

void ble_scan_param_service_init(void);
void ble_scan_param_service_proc(void);
#endif
