#ifndef __BLE_BODY_COMPOSITION_SERVICE_H
#define __BLE_BODY_COMPOSITION_SERVICE_H
#include "include.h"

// Body Composition 0x181B
// PRIMARY_SERVICE, ORG_BLUETOOTH_SERVICE_BODY_COMPOSITION
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_BODY_COMPOSITION_MEASUREMENT, DYNAMIC | INDICATE,
// CLIENT_CHARACTERISTIC_CONFIGURATION, READ | WRITE,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_BODY_COMPOSITION_FEATURE, DYNAMIC | READ,

//
// list service handle ranges
//
#define ATT_SERVICE_ORG_BLUETOOTH_SERVICE_BODY_COMPOSITION_START_HANDLE 0x0007
#define ATT_SERVICE_ORG_BLUETOOTH_SERVICE_BODY_COMPOSITION_END_HANDLE 0x000c

//
// list mapping between characteristics and handles
//
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_BODY_COMPOSITION_MEASUREMENT_01_VALUE_HANDLE 0x0009
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_BODY_COMPOSITION_MEASUREMENT_01_CLIENT_CONFIGURATION_HANDLE 0x000a
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_BODY_COMPOSITION_FEATURE_01_VALUE_HANDLE 0x000c

typedef struct{
    uint8_t feature[4];
    uint16_t meas_client_cfg;
}ble_body_composition_var_t;

void ble_body_composition_service_init(void);
void ble_body_composition_service_proc(void);
void ble_body_composition_service_measurement_indicate(uint8_t *buf, uint16_t buf_size);
#endif
