#ifndef __BLE_CYC_SP_CAD_SERVICE_H
#define __BLE_CYC_SP_CAD_SERVICE_H
#include "include.h"

// Cycling Speed And Cadence  0x1816
// PRIMARY_SERVICE, ORG_BLUETOOTH_SERVICE_CYCLING_SPEED_AND_CADENCE
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_CSC_MEASUREMENT, DYNAMIC | NOTIFY,
// CLIENT_CHARACTERISTIC_CONFIGURATION, READ | WRITE,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_CSC_FEATURE, DYNAMIC | READ,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_SENSOR_LOCATION, DYNAMIC | READ,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_SC_CONTROL_POINT, DYNAMIC | WRITE | INDICATE,
// CLIENT_CHARACTERISTIC_CONFIGURATION, READ | WRITE,

//
// list service handle ranges
//
#define ATT_SERVICE_ORG_BLUETOOTH_SERVICE_CYCLING_SPEED_AND_CADENCE_START_HANDLE 0x0027
#define ATT_SERVICE_ORG_BLUETOOTH_SERVICE_CYCLING_SPEED_AND_CADENCE_END_HANDLE 0x0031

//
// list mapping between characteristics and handles
//
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_CSC_MEASUREMENT_01_VALUE_HANDLE 0x0029
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_CSC_MEASUREMENT_01_CLIENT_CONFIGURATION_HANDLE 0x002a
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_CSC_FEATURE_01_VALUE_HANDLE 0x002c
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_SENSOR_LOCATION_02_VALUE_HANDLE 0x002e
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_SC_CONTROL_POINT_01_VALUE_HANDLE 0x0030
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_SC_CONTROL_POINT_01_CLIENT_CONFIGURATION_HANDLE 0x0031

typedef struct {
    uint8_t feature[2];
    uint16_t meas_client_cfg;
    uint16_t ctr_point_client_cfg;
} ble_cyc_sp_cad_var_t;

void ble_cyc_sp_cad_service_init(void);
void ble_cyc_sp_cad_service_proc(void);
void ble_cyc_sp_cad_service_measurement_notify(uint8_t *buf, uint16_t buf_size);
void ble_cyc_sp_cad_service_control_point_indicate(uint8_t *buf, uint16_t buf_size);
#endif
