#ifndef __BLE_INDOOR_POSITIONING_SERVICE_H
#define __BLE_INDOOR_POSITIONING_SERVICE_H
#include "include.h"

// Indoor Positioning  0x1821
// PRIMARY_SERVICE, ORG_BLUETOOTH_SERVICE_INDOOR_POSITIONING
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_INDOOR_BIKE_DATA, DYNAMIC | READ,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_INDOOR_POSITIONING_CONFIGURATION, DYNAMIC | READ | WRITE | NOTIFY,

//
// list service handle ranges
//
#define ATT_SERVICE_ORG_BLUETOOTH_SERVICE_INDOOR_POSITIONING_START_HANDLE 0x0082
#define ATT_SERVICE_ORG_BLUETOOTH_SERVICE_INDOOR_POSITIONING_END_HANDLE 0x0087

//
// list mapping between characteristics and handles
//
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_INDOOR_BIKE_DATA_01_VALUE_HANDLE 0x0084
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_INDOOR_POSITIONING_CONFIGURATION_01_VALUE_HANDLE 0x0086
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_INDOOR_POSITIONING_CONFIGURATION_01_CLIENT_CONFIGURATION_HANDLE 0x0087

typedef struct{
    uint8_t bik_data[2];
    uint16_t positoning_client_cfg;
}ble_indoor_positioning_var_t;

void ble_indoor_positioning_service_init(void);
void ble_indoor_positioning_service_proc(void);
void ble_indoor_positioning_service_indoor_positioning_notify(uint8_t *buf, uint16_t buf_size);
#endif
