#ifndef __BLE_OBJECT_TRANSFER_SERVICE_H
#define __BLE_OBJECT_TRANSFER_SERVICE_H
#include "include.h"

// Object Transfer  0x1825
// PRIMARY_SERVICE, ORG_BLUETOOTH_SERVICE_OBJECT_TRANSFER
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_OTS_FEATURE, DYNAMIC | READ,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_OBJECT_ACTION_CONTROL_POINT, DYNAMIC | WRITE | INDICATE,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_OBJECT_CHANGED, DYNAMIC | INDICATE,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_OBJECT_FIRST_CREATED, DYNAMIC | READ | WRITE,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_OBJECT_ID, DYNAMIC | READ,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_OBJECT_LAST_MODIFIED, DYNAMIC | READ | WRITE,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_OBJECT_LIST_CONTROL_POINT, DYNAMIC | WRITE | INDICATE,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_OBJECT_LIST_FILTER, DYNAMIC | READ | WRITE,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_OBJECT_NAME, DYNAMIC | READ | WRITE,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_OBJECT_PROPERTIES, DYNAMIC | READ | WRITE,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_OBJECT_SIZE, DYNAMIC | READ,
// CHARACTERISTIC, ORG_BLUETOOTH_CHARACTERISTIC_OBJECT_TYPE, DYNAMIC | READ,

//
// list service handle ranges
//
#define ATT_SERVICE_ORG_BLUETOOTH_SERVICE_OBJECT_TRANSFER_START_HANDLE 0x008b
#define ATT_SERVICE_ORG_BLUETOOTH_SERVICE_OBJECT_TRANSFER_END_HANDLE 0x00a6

//
// list mapping between characteristics and handles
//
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_OTS_FEATURE_01_VALUE_HANDLE 0x008d
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_OBJECT_ACTION_CONTROL_POINT_01_VALUE_HANDLE 0x008f
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_OBJECT_ACTION_CONTROL_POINT_01_CLIENT_CONFIGURATION_HANDLE 0x0090
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_OBJECT_CHANGED_01_VALUE_HANDLE 0x0092
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_OBJECT_CHANGED_01_CLIENT_CONFIGURATION_HANDLE 0x0093
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_OBJECT_FIRST_CREATED_01_VALUE_HANDLE 0x0095
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_OBJECT_ID_01_VALUE_HANDLE 0x0097
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_OBJECT_LAST_MODIFIED_01_VALUE_HANDLE 0x0099
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_OBJECT_LIST_CONTROL_POINT_01_VALUE_HANDLE 0x009b
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_OBJECT_LIST_CONTROL_POINT_01_CLIENT_CONFIGURATION_HANDLE 0x009c
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_OBJECT_LIST_FILTER_01_VALUE_HANDLE 0x009e
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_OBJECT_NAME_01_VALUE_HANDLE 0x00a0
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_OBJECT_PROPERTIES_01_VALUE_HANDLE 0x00a2
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_OBJECT_SIZE_01_VALUE_HANDLE 0x00a4
#define ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_OBJECT_TYPE_01_VALUE_HANDLE 0x00a6

typedef struct{
    uint16_t action_ctr_point_client_cfg;
    uint16_t changed_client_cfg;
    uint16_t list_ctr_point_client_cfg;
}ble_object_transfer_var_t;

void ble_object_transfer_service_init(void);
void ble_object_transfer_service_proc(void);
void ble_object_transfer_service_action_ctr_point_indicate(uint8_t *buf, uint16_t buf_size);
void ble_object_transfer_service_list_ctr_point_indicate(uint8_t *buf, uint16_t buf_size);
void ble_object_transfer_service_change_ctr_indicate(uint8_t *buf, uint16_t buf_size);
#endif
